// this code is autogenerated, do not check it into to your code repository

// ref lib/raylib.ex:8
pub const InitWindowOptions = struct { width: u32, height: u32, title: []u8 };
const beam = @import("beam");

pub fn init_window(options: InitWindowOptions) beam.term {
if (options.width > 0) {}
return beam.make(.ok, .{});
}

pub fn close_window() beam.term {
return beam.make(.ok, .{});
}
